#!/bin/bash
#
#testAutoCorrect
#Run Lint, Run Test
#
#set -e
#set -x


usage() {
  echo "Warning File required"
}

if [ $# -lt 2 ]; then
  usage
  exit 1
fi

# Parse argument.  $1 is the first argument
case $1 in
	"correct")
	if [ $# -ne 2 ]; then
  		echo "Path Required"
  		exit 1
	fi
	swiftlint lint --strict --reporter emoji --config .swiftlint.yml --path $2 > error.txt

	python AutoLint/AutoCorrect.py error.txt
	;;

  "help")
  
  ;;

  *)
    exit 1
    ;;
esac

echo done
