#!/bin/bash
#
#testAutoCorrect
#Run Lint, Run Test
#
#set -e
#set -x


usage() {
  echo "(|help)"
}

if [ $# -lt 1 ]; then
  usage
  exit 1
fi

# Parse argument.  $1 is the first argument
case $1 in
	"correct")
	if [ $# -lt 2 ]; then
  		echo "Path Required"
  		exit 1
	fi

	swiftlint lint --strict --reporter emoji --config .swiftlint.yml --path $2 > error.txt
	python AutoLintFiles/AutoCorrect.py error.txt $3
  rm error.txt
	;;

  "help")
      cat AutoLint/help.txt
  ;;

  *)
    usage
    exit 1
    ;;
esac

